### ISSUE TITLE
How to create dag through restful api or function？

### ISSUE THREAD

**Issue by felixZ828** [apache/airflow-client-go#26]
I cant't find the api which can create dag in the restful apis. Does it support creating dag through API？

**Comment by potiuk** [comment]
No. DAGs can only be created by creating DAG files inDAG folder (so basically use whatever API the shared filesystem provides (Git, NFS, whatever you normally use to create files in the filesystem). 

This is a deliberate decision and part of the security model of Airflow and is unlikely to change.
