### ISSUE TITLE
Request.Execute() return `undefined response type` error

### ISSUE THREAD

**Issue by zbysir** [apache/airflow-client-go#38]
```
➜  ~ curl -i -X GET 'https://airflow.xxx.com/api/v1/dags/xx/dagRuns/xxx' \
-H 'Content-Type: application/json' -H 'Accept: application/json' \
--user "xxx:xxx" \
-d '{}'
HTTP/2 404
date: Wed, 01 Feb 2023 07:42:55 GMT
content-type: application/problem+json
content-length: 263
server: gunicorn
x-robots-tag: noindex, nofollow

{
  "detail": "DAGRun with DAG ID: 'xxx' and DagRun ID: 'xxx' not found",
  "status": 404,
  "title": "DAGRun not found",
  "type": "https://airflow.apache.org/docs/apache-airflow/2.5.0/stable-rest-api-ref.html#section/Errors/NotFound"
}
```

In airflow version 2.5.0, Content-type header in error response is `application/problem+json`, but in this repo the json content-type is check by regexp 
```
jsonCheck = regexp.MustCompile(`(?i:(?:application|text)/(?:vnd\.[^;]+\+)?json)`)
```

The regexp can't match `application/problem+json`, I guess that's the problem.

> About [problem+json](https://datatracker.ietf.org/doc/html/draft-nottingham-http-problem-07)

**Comment by pierrejeambrun** [comment]
Hello @zbysir,

Thank you for reporting this, indeed it looks like the `problem+json` content type is not handled by generated clients. We could also add a post generation step to update the accepted content type for the client. I just opened a [PR](https://github.com/apache/airflow/pull/29476) for that.

In the mean time, the `nethttp.Response` returned object will have everything you need from that failed call, maybe this is the reason this issue wasn't addressed yet.
```
    run, response, error := cli.DAGRunApi.GetDagRun(ctx, "fake", "fake_run").Execute()
```

> In case of an error you need to use 'response' and disregard 'error' which will not be relevant (undefined response type).

**Comment by pierrejeambrun** [comment]
PR has been merged, changes will take effect at the next client release.

Thanks.

**Comment by zbysir** [comment]
Thank you for your proposal, it makes sense.

> Hello @zbysir,
> 
> Thank you for reporting this, indeed it looks like the `problem+json` content type is not handled by generated clients. We could also add a post generation step to update the accepted content type for the client. I just opened a [PR](https://github.com/apache/airflow/pull/29476) for that.
> 
> In the mean time, the `nethttp.Response` returned object will have everything you need from that failed call, maybe this is the reason this issue wasn't addressed yet.
> 
> ```
>     run, response, error := cli.DAGRunApi.GetDagRun(ctx, "fake", "fake_run").Execute()
> ```
> 
> > In case of an error you need to use 'response' and disregard 'error' which will not be relevant (undefined response type).
